name: Publish Node.js Package

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set to the version you use
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@matbuha'  # Replace with your GitHub username or org

    - name: Install dependencies
      run: npm install

    # - name: Build (if necessary)
    #   run: npm run build  # This step can be adjusted or removed as necessary

    - name: Publish to GitHub Packages
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GH_PACKAGES_TOKEN}}
