name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Set this to your main branch or any other branch you want

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'  # Ensure this matches the version you use
          registry-url: @matbuha:registry": "https://npm.pkg.github.com"
      
      - name: Install Dependencies
        run: npm ci  # Uses package-lock.json to install dependencies

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}  # Ensure you use the correct secret for your PAT
