name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Set this to your main branch or any other branch you want

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@matbuha'
      
      - name: Install Dependencies
        run: npm ci  # Uses package-lock.json to install dependencies
      - name: Configure npm
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "@matbuha:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_GitHub_Token }}

      - name: Publish to GitHub Packages
        run: |
          npm login
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_GitHub_Token }}
